# Generated by Django 5.0.4 on 2024-05-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_plane'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='information',
            field=models.TextField(blank=True, verbose_name='Информация'),
        ),
        migrations.AddField(
            model_name='car',
            name='population',
            field=models.PositiveIntegerField(default=0, verbose_name='Лошадиная сила'),
        ),
        migrations.AddField(
            model_name='car',
            name='released',
            field=models.BooleanField(default=True, verbose_name='Выпускается'),
        ),
        migrations.AddField(
            model_name='car',
            name='type',
            field=models.CharField(choices=[('petrol', 'Бензин'), ('diesel', 'Дизель'), ('electricity', 'Электричество'), ('hybrid', 'Гибрид')], default='patrol', max_length=100, verbose_name='Топливо'),
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Марка'),
        ),
    ]
