# Generated by Django 5.0.4 on 2024-05-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_car_information_car_population_car_released_car_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='population',
            new_name='horsepower',
        ),
        migrations.RemoveField(
            model_name='car',
            name='name',
        ),
        migrations.RemoveField(
            model_name='car',
            name='type',
        ),
        migrations.AddField(
            model_name='car',
            name='brand',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Марка'),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel',
            field=models.CharField(choices=[('petrol', 'Бензин'), ('diesel', 'Дизель'), ('electricity', 'Электричество'), ('hybrid', 'Гибрид')], default='patrol', max_length=15, verbose_name='Топливо'),
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Модель'),
        ),
    ]
