# Generated by Django 5.0.4 on 2024-05-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_car_brand_alter_car_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='plane',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Вместимость'),
        ),
        migrations.AddField(
            model_name='plane',
            name='passenger',
            field=models.BooleanField(default=True, verbose_name='Пассажирский'),
        ),
    ]
